version: '2'
services:
  selenium:
    network_mode: "host"
    image: selenium/standalone-chrome
    ports:
     - "127.0.0.1:4444:4444"
  crabby:
    network_mode: "host"
    image: chrissnell/crabby
    environment:
    - CRABBY_CONFIG=/config/config.yaml
    volumes:
     - /etc/crabby:/config
    depends_on:
     - selenium
